project(community)

psoc6_load_application(
  NAME Community-Code-Examples
  TAG  e5c7b1a
)
if(${OS} STREQUAL NOOS)
  include(app/mtb_02_ex01_smartio_rgb.cmake)
  include(app/mtb_02_ex02_pwm_blinkled.cmake)
  include(app/mtb_02_ex03_pwm_brightness_control.cmake)
  include(app/mtb_02_ex04_timer_hal.cmake)
  include(app/mtb_02_ex05_timer_pdl.cmake)
  include(app/mtb_02_ex06_counter_dutycycle.cmake)
  include(app/mtb_02_ex07_i2c_brightness_control.cmake)
  include(app/mtb_02_ex08_spi_master.cmake)
  include(app/mtb_02_ex09_uart.cmake)
  include(app/mtb_03_ex01_psoc6_capsense_button_linearslider.cmake)
  include(app/mtb_03_ex02_psoc6_capsense_gestures_linearslider.cmake)
  include(app/mtb_05_ex01_simple_deep_sleep.cmake)
  include(app/mtb_05_ex02_deep_sleep.cmake)
  include(app/mtb_05_ex03_ulp_sleep.cmake)
  include(app/mtb_05_ex04_hibernate.cmake)
  include(app/mtb_06_ex01_ctdac_wave.cmake)
  include(app/mtb_06_ex02_adc_uart.cmake)
  include(app/mtb_06_ex03_lpcomp_hibernate.cmake)
  include(app/Advanced_Sector_Protection.cmake)
elseif(${OS} STREQUAL FREERTOS)
  include(app/mtb_04_ex01_capsense_led_tcp.cmake)
  #include(app/dht11-freertos.cmake)
  #include(app/oled-freertos.cmake)
endif()
