# Mbed OS includes different MbedTLS version, cannot use lib/mbedtls.cmake
# Intentionally using mbed-tls / MBED_TLS naming to avoid name clash
set(MBED_TLS_DIR ${MBED_OS_DIR}/features/mbedtls)
set(MBED_TLS_SOURCES
  ${MBED_TLS_DIR}/inc/mbedtls/aes.h
  ${MBED_TLS_DIR}/inc/mbedtls/aesni.h
  ${MBED_TLS_DIR}/inc/mbedtls/arc4.h
  ${MBED_TLS_DIR}/inc/mbedtls/aria.h
  ${MBED_TLS_DIR}/inc/mbedtls/asn1.h
  ${MBED_TLS_DIR}/inc/mbedtls/asn1write.h
  ${MBED_TLS_DIR}/inc/mbedtls/base64.h
  ${MBED_TLS_DIR}/inc/mbedtls/bignum.h
  ${MBED_TLS_DIR}/inc/mbedtls/blowfish.h
  ${MBED_TLS_DIR}/inc/mbedtls/bn_mul.h
  ${MBED_TLS_DIR}/inc/mbedtls/camellia.h
  ${MBED_TLS_DIR}/inc/mbedtls/ccm.h
  ${MBED_TLS_DIR}/inc/mbedtls/certs.h
  ${MBED_TLS_DIR}/inc/mbedtls/chacha20.h
  ${MBED_TLS_DIR}/inc/mbedtls/chachapoly.h
  ${MBED_TLS_DIR}/inc/mbedtls/check_config.h
  ${MBED_TLS_DIR}/inc/mbedtls/cipher.h
  ${MBED_TLS_DIR}/inc/mbedtls/cipher_internal.h
  ${MBED_TLS_DIR}/inc/mbedtls/cmac.h
  ${MBED_TLS_DIR}/inc/mbedtls/compat-1.3.h
  ${MBED_TLS_DIR}/inc/mbedtls/config.h
  ${MBED_TLS_DIR}/inc/mbedtls/config-no-entropy.h
  ${MBED_TLS_DIR}/inc/mbedtls/ctr_drbg.h
  ${MBED_TLS_DIR}/inc/mbedtls/debug.h
  ${MBED_TLS_DIR}/inc/mbedtls/des.h
  ${MBED_TLS_DIR}/inc/mbedtls/dhm.h
  ${MBED_TLS_DIR}/inc/mbedtls/ecdh.h
  ${MBED_TLS_DIR}/inc/mbedtls/ecdsa.h
  ${MBED_TLS_DIR}/inc/mbedtls/ecjpake.h
  ${MBED_TLS_DIR}/inc/mbedtls/ecp.h
  ${MBED_TLS_DIR}/inc/mbedtls/ecp_internal.h
  ${MBED_TLS_DIR}/inc/mbedtls/entropy.h
  ${MBED_TLS_DIR}/inc/mbedtls/entropy_poll.h
  ${MBED_TLS_DIR}/inc/mbedtls/error.h
  ${MBED_TLS_DIR}/inc/mbedtls/gcm.h
  ${MBED_TLS_DIR}/inc/mbedtls/havege.h
  ${MBED_TLS_DIR}/inc/mbedtls/hkdf.h
  ${MBED_TLS_DIR}/inc/mbedtls/hmac_drbg.h
  ${MBED_TLS_DIR}/inc/mbedtls/md2.h
  ${MBED_TLS_DIR}/inc/mbedtls/md4.h
  ${MBED_TLS_DIR}/inc/mbedtls/md5.h
  ${MBED_TLS_DIR}/inc/mbedtls/md.h
  ${MBED_TLS_DIR}/inc/mbedtls/md_internal.h
  ${MBED_TLS_DIR}/inc/mbedtls/memory_buffer_alloc.h
  ${MBED_TLS_DIR}/inc/mbedtls/net.h
  ${MBED_TLS_DIR}/inc/mbedtls/net_sockets.h
  ${MBED_TLS_DIR}/inc/mbedtls/nist_kw.h
  ${MBED_TLS_DIR}/inc/mbedtls/oid.h
  ${MBED_TLS_DIR}/inc/mbedtls/padlock.h
  ${MBED_TLS_DIR}/inc/mbedtls/pem.h
  ${MBED_TLS_DIR}/inc/mbedtls/pkcs11.h
  ${MBED_TLS_DIR}/inc/mbedtls/pkcs12.h
  ${MBED_TLS_DIR}/inc/mbedtls/pkcs5.h
  ${MBED_TLS_DIR}/inc/mbedtls/pk.h
  ${MBED_TLS_DIR}/inc/mbedtls/pk_internal.h
  ${MBED_TLS_DIR}/inc/mbedtls/platform.h
  ${MBED_TLS_DIR}/inc/mbedtls/platform_time.h
  ${MBED_TLS_DIR}/inc/mbedtls/platform_util.h
  ${MBED_TLS_DIR}/inc/mbedtls/poly1305.h
  ${MBED_TLS_DIR}/inc/mbedtls/psa_util.h
  ${MBED_TLS_DIR}/inc/mbedtls/ripemd160.h
  ${MBED_TLS_DIR}/inc/mbedtls/rsa.h
  ${MBED_TLS_DIR}/inc/mbedtls/rsa_internal.h
  ${MBED_TLS_DIR}/inc/mbedtls/sha1.h
  ${MBED_TLS_DIR}/inc/mbedtls/sha256.h
  ${MBED_TLS_DIR}/inc/mbedtls/sha512.h
  ${MBED_TLS_DIR}/inc/mbedtls/ssl_cache.h
  ${MBED_TLS_DIR}/inc/mbedtls/ssl_ciphersuites.h
  ${MBED_TLS_DIR}/inc/mbedtls/ssl_cookie.h
  ${MBED_TLS_DIR}/inc/mbedtls/ssl.h
  ${MBED_TLS_DIR}/inc/mbedtls/ssl_internal.h
  ${MBED_TLS_DIR}/inc/mbedtls/ssl_ticket.h
  ${MBED_TLS_DIR}/inc/mbedtls/threading.h
  ${MBED_TLS_DIR}/inc/mbedtls/timing.h
  ${MBED_TLS_DIR}/inc/mbedtls/version.h
  ${MBED_TLS_DIR}/inc/mbedtls/x509_crl.h
  ${MBED_TLS_DIR}/inc/mbedtls/x509_crt.h
  ${MBED_TLS_DIR}/inc/mbedtls/x509_csr.h
  ${MBED_TLS_DIR}/inc/mbedtls/x509.h
  ${MBED_TLS_DIR}/inc/mbedtls/xtea.h
  ${MBED_TLS_DIR}/src/aes.c
  ${MBED_TLS_DIR}/src/aesni.c
  ${MBED_TLS_DIR}/src/arc4.c
  ${MBED_TLS_DIR}/src/aria.c
  ${MBED_TLS_DIR}/src/asn1parse.c
  ${MBED_TLS_DIR}/src/asn1write.c
  ${MBED_TLS_DIR}/src/base64.c
  ${MBED_TLS_DIR}/src/bignum.c
  ${MBED_TLS_DIR}/src/blowfish.c
  ${MBED_TLS_DIR}/src/camellia.c
  ${MBED_TLS_DIR}/src/ccm.c
  ${MBED_TLS_DIR}/src/certs.c
  ${MBED_TLS_DIR}/src/chacha20.c
  ${MBED_TLS_DIR}/src/chachapoly.c
  ${MBED_TLS_DIR}/src/cipher.c
  ${MBED_TLS_DIR}/src/cipher_wrap.c
  ${MBED_TLS_DIR}/src/cmac.c
  ${MBED_TLS_DIR}/src/ctr_drbg.c
  ${MBED_TLS_DIR}/src/debug.c
  ${MBED_TLS_DIR}/src/des.c
  ${MBED_TLS_DIR}/src/dhm.c
  ${MBED_TLS_DIR}/src/ecdh.c
  ${MBED_TLS_DIR}/src/ecdsa.c
  ${MBED_TLS_DIR}/src/ecjpake.c
  ${MBED_TLS_DIR}/src/ecp.c
  ${MBED_TLS_DIR}/src/ecp_curves.c
  ${MBED_TLS_DIR}/src/entropy.c
  ${MBED_TLS_DIR}/src/entropy_poll.c
  ${MBED_TLS_DIR}/src/error.c
  ${MBED_TLS_DIR}/src/gcm.c
  ${MBED_TLS_DIR}/src/havege.c
  ${MBED_TLS_DIR}/src/hkdf.c
  ${MBED_TLS_DIR}/src/hmac_drbg.c
  ${MBED_TLS_DIR}/src/md2.c
  ${MBED_TLS_DIR}/src/md4.c
  ${MBED_TLS_DIR}/src/md5.c
  ${MBED_TLS_DIR}/src/md.c
  ${MBED_TLS_DIR}/src/memory_buffer_alloc.c
  ${MBED_TLS_DIR}/src/net_sockets.c
  ${MBED_TLS_DIR}/src/nist_kw.c
  ${MBED_TLS_DIR}/src/oid.c
  ${MBED_TLS_DIR}/src/padlock.c
  ${MBED_TLS_DIR}/src/pem.c
  ${MBED_TLS_DIR}/src/pk.c
  ${MBED_TLS_DIR}/src/pkcs11.c
  ${MBED_TLS_DIR}/src/pkcs12.c
  ${MBED_TLS_DIR}/src/pkcs5.c
  ${MBED_TLS_DIR}/src/pkparse.c
  ${MBED_TLS_DIR}/src/pk_wrap.c
  ${MBED_TLS_DIR}/src/pkwrite.c
  ${MBED_TLS_DIR}/src/platform.c
  ${MBED_TLS_DIR}/src/platform_util.c
  ${MBED_TLS_DIR}/src/poly1305.c
  ${MBED_TLS_DIR}/src/ripemd160.c
  ${MBED_TLS_DIR}/src/rsa.c
  ${MBED_TLS_DIR}/src/rsa_internal.c
  ${MBED_TLS_DIR}/src/sha1.c
  ${MBED_TLS_DIR}/src/sha256.c
  ${MBED_TLS_DIR}/src/sha512.c
  ${MBED_TLS_DIR}/src/ssl_cache.c
  ${MBED_TLS_DIR}/src/ssl_ciphersuites.c
  ${MBED_TLS_DIR}/src/ssl_cli.c
  ${MBED_TLS_DIR}/src/ssl_cookie.c
  ${MBED_TLS_DIR}/src/ssl_msg.c
  ${MBED_TLS_DIR}/src/ssl_srv.c
  ${MBED_TLS_DIR}/src/ssl_ticket.c
  ${MBED_TLS_DIR}/src/ssl_tls.c
  ${MBED_TLS_DIR}/src/threading.c
  ${MBED_TLS_DIR}/src/timing.c
  ${MBED_TLS_DIR}/src/version.c
  ${MBED_TLS_DIR}/src/version_features.c
  ${MBED_TLS_DIR}/src/x509.c
  ${MBED_TLS_DIR}/src/x509_create.c
  ${MBED_TLS_DIR}/src/x509_crl.c
  ${MBED_TLS_DIR}/src/x509_crt.c
  ${MBED_TLS_DIR}/src/x509_csr.c
  ${MBED_TLS_DIR}/src/x509write_crt.c
  ${MBED_TLS_DIR}/src/x509write_csr.c
  ${MBED_TLS_DIR}/src/xtea.c
)
set(MBED_TLS_INCLUDE_DIRS
  ${MBED_TLS_DIR}
  ${MBED_TLS_DIR}/inc
  # BUG: config.h should not be included directly
  ${MBED_TLS_DIR}/inc/mbedtls
  # TODO: enable HW acceleration
  #${MBED_TLS_DIR}/targets/TARGET_Cypress/TARGET_MXCRYPTO
)
set(MBED_TLS_DEFINES
  -DMBEDTLS_USER_CONFIG_FILE="${PORT_DIR}/mbedtls_user_config.h"
  # required by mbed-os/features/lwipstack/lwip-sys/lwip_tcp_isn.c
  -DMBEDTLS_MD5_C
)
set(MBED_TLS_LINK_LIBRARIES
  mbed-target
)

add_library(mbed-tls STATIC EXCLUDE_FROM_ALL ${MBED_TLS_SOURCES})
target_include_directories(mbed-tls PUBLIC ${MBED_TLS_INCLUDE_DIRS})
target_compile_definitions(mbed-tls PUBLIC ${MBED_TLS_DEFINES})
target_link_libraries(mbed-tls PUBLIC ${MBED_TLS_LINK_LIBRARIES})
