psoc6_load_library(
  NAME mtb-pdl-cat1
  VERSION 2.0.0
)

set(MTB_PDL_CAT1_SOURCES
  ${MTB_PDL_CAT1_DIR}/devices/COMPONENT_CAT1A/include/cy8c4588azi_h675.h
  ${MTB_PDL_CAT1_DIR}/devices/COMPONENT_CAT1A/include/cy8c4588azi_h676.h
  ${MTB_PDL_CAT1_DIR}/devices/COMPONENT_CAT1A/include/cy8c4588azi_h685.h
  ${MTB_PDL_CAT1_DIR}/devices/COMPONENT_CAT1A/include/cy8c4588azi_h686.h
  ${MTB_PDL_CAT1_DIR}/devices/COMPONENT_CAT1A/include/cy8c6016bzi_f04.h
  ${MTB_PDL_CAT1_DIR}/devices/COMPONENT_CAT1A/include/cy8c6036bzi_f04.h
  ${MTB_PDL_CAT1_DIR}/devices/COMPONENT_CAT1A/include/cy8c6116bzi_f54.h
  ${MTB_PDL_CAT1_DIR}/devices/COMPONENT_CAT1A/include/cy8c6117bzi_f34.h
  ${MTB_PDL_CAT1_DIR}/devices/COMPONENT_CAT1A/include/cy8c6117fdi_f02.h
  ${MTB_PDL_CAT1_DIR}/devices/COMPONENT_CAT1A/include/cy8c6117wi_f34.h
  ${MTB_PDL_CAT1_DIR}/devices/COMPONENT_CAT1A/include/cy8c6136bzi_f14.h
  ${MTB_PDL_CAT1_DIR}/devices/COMPONENT_CAT1A/include/cy8c6136bzi_f34.h
  ${MTB_PDL_CAT1_DIR}/devices/COMPONENT_CAT1A/include/cy8c6136fdi_f42.h
  ${MTB_PDL_CAT1_DIR}/devices/COMPONENT_CAT1A/include/cy8c6136fti_f42.h
  ${MTB_PDL_CAT1_DIR}/devices/COMPONENT_CAT1A/include/cy8c6137bzi_f14.h
  ${MTB_PDL_CAT1_DIR}/devices/COMPONENT_CAT1A/include/cy8c6137bzi_f34.h
  ${MTB_PDL_CAT1_DIR}/devices/COMPONENT_CAT1A/include/cy8c6137bzi_f54.h
  ${MTB_PDL_CAT1_DIR}/devices/COMPONENT_CAT1A/include/cy8c6137fdi_f02.h
  ${MTB_PDL_CAT1_DIR}/devices/COMPONENT_CAT1A/include/cy8c6137wi_f54.h
  ${MTB_PDL_CAT1_DIR}/devices/COMPONENT_CAT1A/include/cy8c6144azi_s4f12.h
  ${MTB_PDL_CAT1_DIR}/devices/COMPONENT_CAT1A/include/cy8c6144azi_s4f62.h
  ${MTB_PDL_CAT1_DIR}/devices/COMPONENT_CAT1A/include/cy8c6144azi_s4f82.h
  ${MTB_PDL_CAT1_DIR}/devices/COMPONENT_CAT1A/include/cy8c6144azi_s4f83.h
  ${MTB_PDL_CAT1_DIR}/devices/COMPONENT_CAT1A/include/cy8c6144azi_s4f92.h
  ${MTB_PDL_CAT1_DIR}/devices/COMPONENT_CAT1A/include/cy8c6144azi_s4f93.h
  ${MTB_PDL_CAT1_DIR}/devices/COMPONENT_CAT1A/include/cy8c6144lqi_s4f12.h
  ${MTB_PDL_CAT1_DIR}/devices/COMPONENT_CAT1A/include/cy8c6144lqi_s4f62.h
  ${MTB_PDL_CAT1_DIR}/devices/COMPONENT_CAT1A/include/cy8c6144lqi_s4f82.h
  ${MTB_PDL_CAT1_DIR}/devices/COMPONENT_CAT1A/include/cy8c6144lqi_s4f92.h
  ${MTB_PDL_CAT1_DIR}/devices/COMPONENT_CAT1A/include/cy8c6145azi_s3f02.h
  ${MTB_PDL_CAT1_DIR}/devices/COMPONENT_CAT1A/include/cy8c6145azi_s3f12.h
  ${MTB_PDL_CAT1_DIR}/devices/COMPONENT_CAT1A/include/cy8c6145azi_s3f42.h
  ${MTB_PDL_CAT1_DIR}/devices/COMPONENT_CAT1A/include/cy8c6145azi_s3f62.h
  ${MTB_PDL_CAT1_DIR}/devices/COMPONENT_CAT1A/include/cy8c6145azi_s3f72.h
  ${MTB_PDL_CAT1_DIR}/devices/COMPONENT_CAT1A/include/cy8c6145fni_s3f11.h
  ${MTB_PDL_CAT1_DIR}/devices/COMPONENT_CAT1A/include/cy8c6145fni_s3f41.h
  ${MTB_PDL_CAT1_DIR}/devices/COMPONENT_CAT1A/include/cy8c6145fni_s3f71.h
  ${MTB_PDL_CAT1_DIR}/devices/COMPONENT_CAT1A/include/cy8c6145lqi_s3f02.h
  ${MTB_PDL_CAT1_DIR}/devices/COMPONENT_CAT1A/include/cy8c6145lqi_s3f12.h
  ${MTB_PDL_CAT1_DIR}/devices/COMPONENT_CAT1A/include/cy8c6145lqi_s3f42.h
  ${MTB_PDL_CAT1_DIR}/devices/COMPONENT_CAT1A/include/cy8c6145lqi_s3f62.h
  ${MTB_PDL_CAT1_DIR}/devices/COMPONENT_CAT1A/include/cy8c6145lqi_s3f72.h
  ${MTB_PDL_CAT1_DIR}/devices/COMPONENT_CAT1A/include/cy8c6148azi_s2f44.h
  ${MTB_PDL_CAT1_DIR}/devices/COMPONENT_CAT1A/include/cy8c6148bzi_s2f44.h
  ${MTB_PDL_CAT1_DIR}/devices/COMPONENT_CAT1A/include/cy8c6148fni_s2f43.h
  ${MTB_PDL_CAT1_DIR}/devices/COMPONENT_CAT1A/include/cy8c614aazi_s2f04.h
  ${MTB_PDL_CAT1_DIR}/devices/COMPONENT_CAT1A/include/cy8c614aazi_s2f14.h
  ${MTB_PDL_CAT1_DIR}/devices/COMPONENT_CAT1A/include/cy8c614aazi_s2f44.h
  ${MTB_PDL_CAT1_DIR}/devices/COMPONENT_CAT1A/include/cy8c614abzi_s2f04.h
  ${MTB_PDL_CAT1_DIR}/devices/COMPONENT_CAT1A/include/cy8c614abzi_s2f44.h
  ${MTB_PDL_CAT1_DIR}/devices/COMPONENT_CAT1A/include/cy8c614afni_s2f03.h
  ${MTB_PDL_CAT1_DIR}/devices/COMPONENT_CAT1A/include/cy8c614afni_s2f43.h
  ${MTB_PDL_CAT1_DIR}/devices/COMPONENT_CAT1A/include/cy8c6244azi_s4d12.h
  ${MTB_PDL_CAT1_DIR}/devices/COMPONENT_CAT1A/include/cy8c6244azi_s4d62.h
  ${MTB_PDL_CAT1_DIR}/devices/COMPONENT_CAT1A/include/cy8c6244azi_s4d82.h
  ${MTB_PDL_CAT1_DIR}/devices/COMPONENT_CAT1A/include/cy8c6244azi_s4d83.h
  ${MTB_PDL_CAT1_DIR}/devices/COMPONENT_CAT1A/include/cy8c6244azi_s4d92.h
  ${MTB_PDL_CAT1_DIR}/devices/COMPONENT_CAT1A/include/cy8c6244azi_s4d93.h
  ${MTB_PDL_CAT1_DIR}/devices/COMPONENT_CAT1A/include/cy8c6244lqi_s4d12.h
  ${MTB_PDL_CAT1_DIR}/devices/COMPONENT_CAT1A/include/cy8c6244lqi_s4d62.h
  ${MTB_PDL_CAT1_DIR}/devices/COMPONENT_CAT1A/include/cy8c6244lqi_s4d82.h
  ${MTB_PDL_CAT1_DIR}/devices/COMPONENT_CAT1A/include/cy8c6244lqi_s4d92.h
  ${MTB_PDL_CAT1_DIR}/devices/COMPONENT_CAT1A/include/cy8c6245azi_s3d02.h
  ${MTB_PDL_CAT1_DIR}/devices/COMPONENT_CAT1A/include/cy8c6245azi_s3d12.h
  ${MTB_PDL_CAT1_DIR}/devices/COMPONENT_CAT1A/include/cy8c6245azi_s3d42.h
  ${MTB_PDL_CAT1_DIR}/devices/COMPONENT_CAT1A/include/cy8c6245azi_s3d62.h
  ${MTB_PDL_CAT1_DIR}/devices/COMPONENT_CAT1A/include/cy8c6245azi_s3d72.h
  ${MTB_PDL_CAT1_DIR}/devices/COMPONENT_CAT1A/include/cy8c6245fni_s3d11.h
  ${MTB_PDL_CAT1_DIR}/devices/COMPONENT_CAT1A/include/cy8c6245fni_s3d41.h
  ${MTB_PDL_CAT1_DIR}/devices/COMPONENT_CAT1A/include/cy8c6245fni_s3d71.h
  ${MTB_PDL_CAT1_DIR}/devices/COMPONENT_CAT1A/include/cy8c6245lqi_s3d02.h
  ${MTB_PDL_CAT1_DIR}/devices/COMPONENT_CAT1A/include/cy8c6245lqi_s3d12.h
  ${MTB_PDL_CAT1_DIR}/devices/COMPONENT_CAT1A/include/cy8c6245lqi_s3d42.h
  ${MTB_PDL_CAT1_DIR}/devices/COMPONENT_CAT1A/include/cy8c6245lqi_s3d62.h
  ${MTB_PDL_CAT1_DIR}/devices/COMPONENT_CAT1A/include/cy8c6245lqi_s3d72.h
  ${MTB_PDL_CAT1_DIR}/devices/COMPONENT_CAT1A/include/cy8c6246bzi_d04.h
  ${MTB_PDL_CAT1_DIR}/devices/COMPONENT_CAT1A/include/cy8c6247bfi_d54.h
  ${MTB_PDL_CAT1_DIR}/devices/COMPONENT_CAT1A/include/cy8c6247bzi_aud54.h
  ${MTB_PDL_CAT1_DIR}/devices/COMPONENT_CAT1A/include/cy8c6247bzi_d34.h
  ${MTB_PDL_CAT1_DIR}/devices/COMPONENT_CAT1A/include/cy8c6247bzi_d44.h
  ${MTB_PDL_CAT1_DIR}/devices/COMPONENT_CAT1A/include/cy8c6247bzi_d54.h
  ${MTB_PDL_CAT1_DIR}/devices/COMPONENT_CAT1A/include/cy8c6247fdi_d02.h
  ${MTB_PDL_CAT1_DIR}/devices/COMPONENT_CAT1A/include/cy8c6247fdi_d32.h
  ${MTB_PDL_CAT1_DIR}/devices/COMPONENT_CAT1A/include/cy8c6247fdi_d52.h
  ${MTB_PDL_CAT1_DIR}/devices/COMPONENT_CAT1A/include/cy8c6247fti_d52.h
  ${MTB_PDL_CAT1_DIR}/devices/COMPONENT_CAT1A/include/cy8c6247wi_d54.h
  ${MTB_PDL_CAT1_DIR}/devices/COMPONENT_CAT1A/include/cy8c6248azi_d14.h
  ${MTB_PDL_CAT1_DIR}/devices/COMPONENT_CAT1A/include/cy8c6248azi_d44.h
  ${MTB_PDL_CAT1_DIR}/devices/COMPONENT_CAT1A/include/cy8c6248azi_s2d14.h
  ${MTB_PDL_CAT1_DIR}/devices/COMPONENT_CAT1A/include/cy8c6248azi_s2d44.h
  ${MTB_PDL_CAT1_DIR}/devices/COMPONENT_CAT1A/include/cy8c6248bzi_d44.h
  ${MTB_PDL_CAT1_DIR}/devices/COMPONENT_CAT1A/include/cy8c6248bzi_s2d44.h
  ${MTB_PDL_CAT1_DIR}/devices/COMPONENT_CAT1A/include/cy8c6248fni_d43.h
  ${MTB_PDL_CAT1_DIR}/devices/COMPONENT_CAT1A/include/cy8c6248fni_s2d43.h
  ${MTB_PDL_CAT1_DIR}/devices/COMPONENT_CAT1A/include/cy8c624aazi_d14.h
  ${MTB_PDL_CAT1_DIR}/devices/COMPONENT_CAT1A/include/cy8c624aazi_d44.h
  ${MTB_PDL_CAT1_DIR}/devices/COMPONENT_CAT1A/include/cy8c624aazi_s2d14.h
  ${MTB_PDL_CAT1_DIR}/devices/COMPONENT_CAT1A/include/cy8c624aazi_s2d44.h
  ${MTB_PDL_CAT1_DIR}/devices/COMPONENT_CAT1A/include/cy8c624abzi_d04.h
  ${MTB_PDL_CAT1_DIR}/devices/COMPONENT_CAT1A/include/cy8c624abzi_d14.h
  ${MTB_PDL_CAT1_DIR}/devices/COMPONENT_CAT1A/include/cy8c624abzi_d44.h
  ${MTB_PDL_CAT1_DIR}/devices/COMPONENT_CAT1A/include/cy8c624abzi_s2d04.h
  ${MTB_PDL_CAT1_DIR}/devices/COMPONENT_CAT1A/include/cy8c624abzi_s2d14.h
  ${MTB_PDL_CAT1_DIR}/devices/COMPONENT_CAT1A/include/cy8c624abzi_s2d44.h
  ${MTB_PDL_CAT1_DIR}/devices/COMPONENT_CAT1A/include/cy8c624abzi_s2d44a0.h
  ${MTB_PDL_CAT1_DIR}/devices/COMPONENT_CAT1A/include/cy8c624afni_d43.h
  ${MTB_PDL_CAT1_DIR}/devices/COMPONENT_CAT1A/include/cy8c624afni_s2d43.h
  ${MTB_PDL_CAT1_DIR}/devices/COMPONENT_CAT1A/include/cy8c624alqi_d42.h
  ${MTB_PDL_CAT1_DIR}/devices/COMPONENT_CAT1A/include/cy8c6316bzi_blf03.h
  ${MTB_PDL_CAT1_DIR}/devices/COMPONENT_CAT1A/include/cy8c6316bzi_blf04.h
  ${MTB_PDL_CAT1_DIR}/devices/COMPONENT_CAT1A/include/cy8c6316bzi_blf53.h
  ${MTB_PDL_CAT1_DIR}/devices/COMPONENT_CAT1A/include/cy8c6316bzi_blf54.h
  ${MTB_PDL_CAT1_DIR}/devices/COMPONENT_CAT1A/include/cy8c6336bzi_bld13.h
  ${MTB_PDL_CAT1_DIR}/devices/COMPONENT_CAT1A/include/cy8c6336bzi_bld14.h
  ${MTB_PDL_CAT1_DIR}/devices/COMPONENT_CAT1A/include/cy8c6336bzi_blf03.h
  ${MTB_PDL_CAT1_DIR}/devices/COMPONENT_CAT1A/include/cy8c6336bzi_blf04.h
  ${MTB_PDL_CAT1_DIR}/devices/COMPONENT_CAT1A/include/cy8c6336bzi_bud13.h
  ${MTB_PDL_CAT1_DIR}/devices/COMPONENT_CAT1A/include/cy8c6336lqi_blf02.h
  ${MTB_PDL_CAT1_DIR}/devices/COMPONENT_CAT1A/include/cy8c6336lqi_blf42.h
  ${MTB_PDL_CAT1_DIR}/devices/COMPONENT_CAT1A/include/cy8c6337bzi_blf13.h
  ${MTB_PDL_CAT1_DIR}/devices/COMPONENT_CAT1A/include/cy8c6347bzi_bld33.h
  ${MTB_PDL_CAT1_DIR}/devices/COMPONENT_CAT1A/include/cy8c6347bzi_bld34.h
  ${MTB_PDL_CAT1_DIR}/devices/COMPONENT_CAT1A/include/cy8c6347bzi_bld43.h
  ${MTB_PDL_CAT1_DIR}/devices/COMPONENT_CAT1A/include/cy8c6347bzi_bld44.h
  ${MTB_PDL_CAT1_DIR}/devices/COMPONENT_CAT1A/include/cy8c6347bzi_bld53.h
  ${MTB_PDL_CAT1_DIR}/devices/COMPONENT_CAT1A/include/cy8c6347bzi_bld54.h
  ${MTB_PDL_CAT1_DIR}/devices/COMPONENT_CAT1A/include/cy8c6347bzi_bud33.h
  ${MTB_PDL_CAT1_DIR}/devices/COMPONENT_CAT1A/include/cy8c6347bzi_bud43.h
  ${MTB_PDL_CAT1_DIR}/devices/COMPONENT_CAT1A/include/cy8c6347bzi_bud53.h
  ${MTB_PDL_CAT1_DIR}/devices/COMPONENT_CAT1A/include/cy8c6347fmi_bld13.h
  ${MTB_PDL_CAT1_DIR}/devices/COMPONENT_CAT1A/include/cy8c6347fmi_bld33.h
  ${MTB_PDL_CAT1_DIR}/devices/COMPONENT_CAT1A/include/cy8c6347fmi_bld43.h
  ${MTB_PDL_CAT1_DIR}/devices/COMPONENT_CAT1A/include/cy8c6347fmi_bld43.h
  ${MTB_PDL_CAT1_DIR}/devices/COMPONENT_CAT1A/include/cy8c6347fmi_bld53.h
  ${MTB_PDL_CAT1_DIR}/devices/COMPONENT_CAT1A/include/cy8c6347fmi_bld53.h
  ${MTB_PDL_CAT1_DIR}/devices/COMPONENT_CAT1A/include/cy8c6347fmi_bud13.h
  ${MTB_PDL_CAT1_DIR}/devices/COMPONENT_CAT1A/include/cy8c6347fmi_bud13.h
  ${MTB_PDL_CAT1_DIR}/devices/COMPONENT_CAT1A/include/cy8c6347fmi_bud33.h
  ${MTB_PDL_CAT1_DIR}/devices/COMPONENT_CAT1A/include/cy8c6347fmi_bud33.h
  ${MTB_PDL_CAT1_DIR}/devices/COMPONENT_CAT1A/include/cy8c6347fmi_bud43.h
  ${MTB_PDL_CAT1_DIR}/devices/COMPONENT_CAT1A/include/cy8c6347fmi_bud53.h
  ${MTB_PDL_CAT1_DIR}/devices/COMPONENT_CAT1A/include/cy8c6347lqi_bld52.h
  ${MTB_PDL_CAT1_DIR}/devices/COMPONENT_CAT1A/include/cy8c637bzi_bld74.h
  ${MTB_PDL_CAT1_DIR}/devices/COMPONENT_CAT1A/include/cy8c637bzi_md76.h
  ${MTB_PDL_CAT1_DIR}/devices/COMPONENT_CAT1A/include/cy8c637fmi_bld73.h
  ${MTB_PDL_CAT1_DIR}/devices/COMPONENT_CAT1A/include/cy8c68237bz_ble.h
  ${MTB_PDL_CAT1_DIR}/devices/COMPONENT_CAT1A/include/cy8c68237fm_ble.h
  ${MTB_PDL_CAT1_DIR}/devices/COMPONENT_CAT1A/include/cy_device_common.h
  ${MTB_PDL_CAT1_DIR}/devices/COMPONENT_CAT1A/include/cy_device_headers.h
  ${MTB_PDL_CAT1_DIR}/devices/COMPONENT_CAT1A/include/cyb06445lqi_s3d42.h
  ${MTB_PDL_CAT1_DIR}/devices/COMPONENT_CAT1A/include/cyb06447bzi_bld53.h
  ${MTB_PDL_CAT1_DIR}/devices/COMPONENT_CAT1A/include/cyb06447bzi_bld54.h
  ${MTB_PDL_CAT1_DIR}/devices/COMPONENT_CAT1A/include/cyb06447bzi_d54.h
  ${MTB_PDL_CAT1_DIR}/devices/COMPONENT_CAT1A/include/cyb0644abzi_s2d44.h
  ${MTB_PDL_CAT1_DIR}/devices/COMPONENT_CAT1A/include/cyble_416045_02.h
  ${MTB_PDL_CAT1_DIR}/devices/COMPONENT_CAT1A/include/cys0644abzi_s2d44.h
  ${MTB_PDL_CAT1_DIR}/devices/COMPONENT_CAT1A/include/gpio_psoc6_01_104_m_csp_ble.h
  ${MTB_PDL_CAT1_DIR}/devices/COMPONENT_CAT1A/include/gpio_psoc6_01_104_m_csp_ble_usb.h
  ${MTB_PDL_CAT1_DIR}/devices/COMPONENT_CAT1A/include/gpio_psoc6_01_116_bga_ble.h
  ${MTB_PDL_CAT1_DIR}/devices/COMPONENT_CAT1A/include/gpio_psoc6_01_116_bga_usb.h
  ${MTB_PDL_CAT1_DIR}/devices/COMPONENT_CAT1A/include/gpio_psoc6_01_124_bga.h
  ${MTB_PDL_CAT1_DIR}/devices/COMPONENT_CAT1A/include/gpio_psoc6_01_124_bga_sip.h
  ${MTB_PDL_CAT1_DIR}/devices/COMPONENT_CAT1A/include/gpio_psoc6_01_43_smt.h
  ${MTB_PDL_CAT1_DIR}/devices/COMPONENT_CAT1A/include/gpio_psoc6_01_68_qfn_ble.h
  ${MTB_PDL_CAT1_DIR}/devices/COMPONENT_CAT1A/include/gpio_psoc6_01_80_wlcsp.h
  ${MTB_PDL_CAT1_DIR}/devices/COMPONENT_CAT1A/include/gpio_psoc6_02_100_wlcsp.h
  ${MTB_PDL_CAT1_DIR}/devices/COMPONENT_CAT1A/include/gpio_psoc6_02_124_bga.h
  ${MTB_PDL_CAT1_DIR}/devices/COMPONENT_CAT1A/include/gpio_psoc6_02_128_tqfp.h
  ${MTB_PDL_CAT1_DIR}/devices/COMPONENT_CAT1A/include/gpio_psoc6_02_68_qfn.h
  ${MTB_PDL_CAT1_DIR}/devices/COMPONENT_CAT1A/include/gpio_psoc6_03_100_tqfp.h
  ${MTB_PDL_CAT1_DIR}/devices/COMPONENT_CAT1A/include/gpio_psoc6_03_49_wlcsp.h
  ${MTB_PDL_CAT1_DIR}/devices/COMPONENT_CAT1A/include/gpio_psoc6_03_68_qfn.h
  ${MTB_PDL_CAT1_DIR}/devices/COMPONENT_CAT1A/include/gpio_psoc6_04_64_tqfp.h
  ${MTB_PDL_CAT1_DIR}/devices/COMPONENT_CAT1A/include/gpio_psoc6_04_68_qfn.h
  ${MTB_PDL_CAT1_DIR}/devices/COMPONENT_CAT1A/include/gpio_psoc6_04_80_tqfp.h
  ${MTB_PDL_CAT1_DIR}/devices/COMPONENT_CAT1A/include/psoc6_01_config.h
  ${MTB_PDL_CAT1_DIR}/devices/COMPONENT_CAT1A/include/psoc6_02_config.h
  ${MTB_PDL_CAT1_DIR}/devices/COMPONENT_CAT1A/include/psoc6_03_config.h
  ${MTB_PDL_CAT1_DIR}/devices/COMPONENT_CAT1A/include/psoc6_04_config.h
  ${MTB_PDL_CAT1_DIR}/devices/COMPONENT_CAT1A/include/ip/cyip_backup.h
  ${MTB_PDL_CAT1_DIR}/devices/COMPONENT_CAT1A/include/ip/cyip_ble.h
  ${MTB_PDL_CAT1_DIR}/devices/COMPONENT_CAT1A/include/ip/cyip_canfd.h
  ${MTB_PDL_CAT1_DIR}/devices/COMPONENT_CAT1A/include/ip/cyip_cpuss.h
  ${MTB_PDL_CAT1_DIR}/devices/COMPONENT_CAT1A/include/ip/cyip_cpuss_v2.h
  ${MTB_PDL_CAT1_DIR}/devices/COMPONENT_CAT1A/include/ip/cyip_crypto.h
  ${MTB_PDL_CAT1_DIR}/devices/COMPONENT_CAT1A/include/ip/cyip_crypto_v2.h
  ${MTB_PDL_CAT1_DIR}/devices/COMPONENT_CAT1A/include/ip/cyip_csd.h
  ${MTB_PDL_CAT1_DIR}/devices/COMPONENT_CAT1A/include/ip/cyip_ctbm.h
  ${MTB_PDL_CAT1_DIR}/devices/COMPONENT_CAT1A/include/ip/cyip_ctbm_v2.h
  ${MTB_PDL_CAT1_DIR}/devices/COMPONENT_CAT1A/include/ip/cyip_ctdac.h
  ${MTB_PDL_CAT1_DIR}/devices/COMPONENT_CAT1A/include/ip/cyip_ctdac_v2.h
  ${MTB_PDL_CAT1_DIR}/devices/COMPONENT_CAT1A/include/ip/cyip_dmac_v2.h
  ${MTB_PDL_CAT1_DIR}/devices/COMPONENT_CAT1A/include/ip/cyip_dw.h
  ${MTB_PDL_CAT1_DIR}/devices/COMPONENT_CAT1A/include/ip/cyip_dw_v2.h
  ${MTB_PDL_CAT1_DIR}/devices/COMPONENT_CAT1A/include/ip/cyip_efuse_data_psoc6_01.h
  ${MTB_PDL_CAT1_DIR}/devices/COMPONENT_CAT1A/include/ip/cyip_efuse_data_psoc6_02.h
  ${MTB_PDL_CAT1_DIR}/devices/COMPONENT_CAT1A/include/ip/cyip_efuse_data_psoc6_03.h
  ${MTB_PDL_CAT1_DIR}/devices/COMPONENT_CAT1A/include/ip/cyip_efuse_data_psoc6_04.h
  ${MTB_PDL_CAT1_DIR}/devices/COMPONENT_CAT1A/include/ip/cyip_efuse.h
  ${MTB_PDL_CAT1_DIR}/devices/COMPONENT_CAT1A/include/ip/cyip_fault.h
  ${MTB_PDL_CAT1_DIR}/devices/COMPONENT_CAT1A/include/ip/cyip_fault_v2.h
  ${MTB_PDL_CAT1_DIR}/devices/COMPONENT_CAT1A/include/ip/cyip_flashc.h
  ${MTB_PDL_CAT1_DIR}/devices/COMPONENT_CAT1A/include/ip/cyip_flashc_v2.h
  ${MTB_PDL_CAT1_DIR}/devices/COMPONENT_CAT1A/include/ip/cyip_gpio.h
  ${MTB_PDL_CAT1_DIR}/devices/COMPONENT_CAT1A/include/ip/cyip_gpio_v2.h
  ${MTB_PDL_CAT1_DIR}/devices/COMPONENT_CAT1A/include/ip/cyip_headers.h
  ${MTB_PDL_CAT1_DIR}/devices/COMPONENT_CAT1A/include/ip/cyip_hsiom.h
  ${MTB_PDL_CAT1_DIR}/devices/COMPONENT_CAT1A/include/ip/cyip_hsiom_v2.h
  ${MTB_PDL_CAT1_DIR}/devices/COMPONENT_CAT1A/include/ip/cyip_i2s.h
  ${MTB_PDL_CAT1_DIR}/devices/COMPONENT_CAT1A/include/ip/cyip_ipc.h
  ${MTB_PDL_CAT1_DIR}/devices/COMPONENT_CAT1A/include/ip/cyip_ipc_v2.h
  ${MTB_PDL_CAT1_DIR}/devices/COMPONENT_CAT1A/include/ip/cyip_lcd.h
  ${MTB_PDL_CAT1_DIR}/devices/COMPONENT_CAT1A/include/ip/cyip_lcd_v2.h
  ${MTB_PDL_CAT1_DIR}/devices/COMPONENT_CAT1A/include/ip/cyip_lpcomp.h
  ${MTB_PDL_CAT1_DIR}/devices/COMPONENT_CAT1A/include/ip/cyip_pass.h
  ${MTB_PDL_CAT1_DIR}/devices/COMPONENT_CAT1A/include/ip/cyip_pass_v2.h
  ${MTB_PDL_CAT1_DIR}/devices/COMPONENT_CAT1A/include/ip/cyip_pdm.h
  ${MTB_PDL_CAT1_DIR}/devices/COMPONENT_CAT1A/include/ip/cyip_peri.h
  ${MTB_PDL_CAT1_DIR}/devices/COMPONENT_CAT1A/include/ip/cyip_peri_ms_v2.h
  ${MTB_PDL_CAT1_DIR}/devices/COMPONENT_CAT1A/include/ip/cyip_peri_v2.h
  ${MTB_PDL_CAT1_DIR}/devices/COMPONENT_CAT1A/include/ip/cyip_profile.h
  ${MTB_PDL_CAT1_DIR}/devices/COMPONENT_CAT1A/include/ip/cyip_prot.h
  ${MTB_PDL_CAT1_DIR}/devices/COMPONENT_CAT1A/include/ip/cyip_prot_v2.h
  ${MTB_PDL_CAT1_DIR}/devices/COMPONENT_CAT1A/include/ip/cyip_sar.h
  ${MTB_PDL_CAT1_DIR}/devices/COMPONENT_CAT1A/include/ip/cyip_sar_v2.h
  ${MTB_PDL_CAT1_DIR}/devices/COMPONENT_CAT1A/include/ip/cyip_scb.h
  ${MTB_PDL_CAT1_DIR}/devices/COMPONENT_CAT1A/include/ip/cyip_sdhc.h
  ${MTB_PDL_CAT1_DIR}/devices/COMPONENT_CAT1A/include/ip/cyip_sflash.h
  ${MTB_PDL_CAT1_DIR}/devices/COMPONENT_CAT1A/include/ip/cyip_smartio.h
  ${MTB_PDL_CAT1_DIR}/devices/COMPONENT_CAT1A/include/ip/cyip_smartio_v2.h
  ${MTB_PDL_CAT1_DIR}/devices/COMPONENT_CAT1A/include/ip/cyip_smif.h
  ${MTB_PDL_CAT1_DIR}/devices/COMPONENT_CAT1A/include/ip/cyip_srss.h
  ${MTB_PDL_CAT1_DIR}/devices/COMPONENT_CAT1A/include/ip/cyip_tcpwm.h
  ${MTB_PDL_CAT1_DIR}/devices/COMPONENT_CAT1A/include/ip/cyip_tcpwm_v2.h
  ${MTB_PDL_CAT1_DIR}/devices/COMPONENT_CAT1A/include/ip/cyip_udb.h
  ${MTB_PDL_CAT1_DIR}/devices/COMPONENT_CAT1A/include/ip/cyip_usbfs.h
  ${MTB_PDL_CAT1_DIR}/drivers/include/cy_ble_clk.h
  ${MTB_PDL_CAT1_DIR}/drivers/include/cy_canfd.h
  ${MTB_PDL_CAT1_DIR}/drivers/include/cy_crypto.h
  ${MTB_PDL_CAT1_DIR}/drivers/include/cy_crypto_common.h
  ${MTB_PDL_CAT1_DIR}/drivers/include/cy_crypto_core.h
  ${MTB_PDL_CAT1_DIR}/drivers/include/cy_crypto_core_aes.h
  ${MTB_PDL_CAT1_DIR}/drivers/include/cy_crypto_core_aes_v1.h
  ${MTB_PDL_CAT1_DIR}/drivers/include/cy_crypto_core_aes_v2.h
  ${MTB_PDL_CAT1_DIR}/drivers/include/cy_crypto_core_cmac.h
  ${MTB_PDL_CAT1_DIR}/drivers/include/cy_crypto_core_cmac_v1.h
  ${MTB_PDL_CAT1_DIR}/drivers/include/cy_crypto_core_cmac_v2.h
  ${MTB_PDL_CAT1_DIR}/drivers/include/cy_crypto_core_crc.h
  ${MTB_PDL_CAT1_DIR}/drivers/include/cy_crypto_core_crc_v1.h
  ${MTB_PDL_CAT1_DIR}/drivers/include/cy_crypto_core_crc_v2.h
  ${MTB_PDL_CAT1_DIR}/drivers/include/cy_crypto_core_des.h
  ${MTB_PDL_CAT1_DIR}/drivers/include/cy_crypto_core_des_v1.h
  ${MTB_PDL_CAT1_DIR}/drivers/include/cy_crypto_core_des_v2.h
  ${MTB_PDL_CAT1_DIR}/drivers/include/cy_crypto_core_ecc.h
  ${MTB_PDL_CAT1_DIR}/drivers/include/cy_crypto_core_ecc_nist_p.h
  ${MTB_PDL_CAT1_DIR}/drivers/include/cy_crypto_core_hmac.h
  ${MTB_PDL_CAT1_DIR}/drivers/include/cy_crypto_core_hmac_v1.h
  ${MTB_PDL_CAT1_DIR}/drivers/include/cy_crypto_core_hmac_v2.h
  ${MTB_PDL_CAT1_DIR}/drivers/include/cy_crypto_core_hw.h
  ${MTB_PDL_CAT1_DIR}/drivers/include/cy_crypto_core_hw_v1.h
  ${MTB_PDL_CAT1_DIR}/drivers/include/cy_crypto_core_hw_v2.h
  ${MTB_PDL_CAT1_DIR}/drivers/include/cy_crypto_core_hw_vu.h
  ${MTB_PDL_CAT1_DIR}/drivers/include/cy_crypto_core_mem.h
  ${MTB_PDL_CAT1_DIR}/drivers/include/cy_crypto_core_mem_v1.h
  ${MTB_PDL_CAT1_DIR}/drivers/include/cy_crypto_core_mem_v2.h
  ${MTB_PDL_CAT1_DIR}/drivers/include/cy_crypto_core_prng.h
  ${MTB_PDL_CAT1_DIR}/drivers/include/cy_crypto_core_prng_v1.h
  ${MTB_PDL_CAT1_DIR}/drivers/include/cy_crypto_core_prng_v2.h
  ${MTB_PDL_CAT1_DIR}/drivers/include/cy_crypto_core_rsa.h
  ${MTB_PDL_CAT1_DIR}/drivers/include/cy_crypto_core_sha.h
  ${MTB_PDL_CAT1_DIR}/drivers/include/cy_crypto_core_sha_v1.h
  ${MTB_PDL_CAT1_DIR}/drivers/include/cy_crypto_core_sha_v2.h
  ${MTB_PDL_CAT1_DIR}/drivers/include/cy_crypto_core_trng.h
  ${MTB_PDL_CAT1_DIR}/drivers/include/cy_crypto_core_trng_config_v1.h
  ${MTB_PDL_CAT1_DIR}/drivers/include/cy_crypto_core_trng_config_v2.h
  ${MTB_PDL_CAT1_DIR}/drivers/include/cy_crypto_core_trng_v1.h
  ${MTB_PDL_CAT1_DIR}/drivers/include/cy_crypto_core_trng_v2.h
  ${MTB_PDL_CAT1_DIR}/drivers/include/cy_crypto_core_vu.h
  ${MTB_PDL_CAT1_DIR}/drivers/include/cy_crypto_server.h
  ${MTB_PDL_CAT1_DIR}/drivers/include/cy_csd.h
  ${MTB_PDL_CAT1_DIR}/drivers/include/cy_ctb.h
  ${MTB_PDL_CAT1_DIR}/drivers/include/cy_ctdac.h
  ${MTB_PDL_CAT1_DIR}/drivers/include/cy_device.h
  ${MTB_PDL_CAT1_DIR}/drivers/include/cy_dma.h
  ${MTB_PDL_CAT1_DIR}/drivers/include/cy_dmac.h
  ${MTB_PDL_CAT1_DIR}/drivers/include/cy_efuse.h
  ${MTB_PDL_CAT1_DIR}/drivers/include/cy_flash.h
  ${MTB_PDL_CAT1_DIR}/drivers/include/cy_gpio.h
  ${MTB_PDL_CAT1_DIR}/drivers/include/cy_i2s.h
  ${MTB_PDL_CAT1_DIR}/drivers/include/cy_ipc_drv.h
  ${MTB_PDL_CAT1_DIR}/drivers/include/cy_ipc_pipe.h
  ${MTB_PDL_CAT1_DIR}/drivers/include/cy_ipc_sema.h
  ${MTB_PDL_CAT1_DIR}/drivers/include/cy_lpcomp.h
  ${MTB_PDL_CAT1_DIR}/drivers/include/cy_lvd.h
  ${MTB_PDL_CAT1_DIR}/drivers/include/cy_mcwdt.h
  ${MTB_PDL_CAT1_DIR}/drivers/include/cy_pdl.h
  ${MTB_PDL_CAT1_DIR}/drivers/include/cy_pdm_pcm.h
  ${MTB_PDL_CAT1_DIR}/drivers/include/cy_pra.h
  ${MTB_PDL_CAT1_DIR}/drivers/include/cy_pra_cfg.h
  ${MTB_PDL_CAT1_DIR}/drivers/include/cy_profile.h
  ${MTB_PDL_CAT1_DIR}/drivers/include/cy_prot.h
  ${MTB_PDL_CAT1_DIR}/drivers/include/cy_rtc.h
  ${MTB_PDL_CAT1_DIR}/drivers/include/cy_sar.h
  ${MTB_PDL_CAT1_DIR}/drivers/include/cy_scb_common.h
  ${MTB_PDL_CAT1_DIR}/drivers/include/cy_scb_ezi2c.h
  ${MTB_PDL_CAT1_DIR}/drivers/include/cy_scb_i2c.h
  ${MTB_PDL_CAT1_DIR}/drivers/include/cy_scb_spi.h
  ${MTB_PDL_CAT1_DIR}/drivers/include/cy_scb_uart.h
  ${MTB_PDL_CAT1_DIR}/drivers/include/cy_sd_host.h
  ${MTB_PDL_CAT1_DIR}/drivers/include/cy_seglcd.h
  ${MTB_PDL_CAT1_DIR}/drivers/include/cy_smartio.h
  ${MTB_PDL_CAT1_DIR}/drivers/include/cy_smif.h
  ${MTB_PDL_CAT1_DIR}/drivers/include/cy_smif_memslot.h
  ${MTB_PDL_CAT1_DIR}/drivers/include/cy_sysanalog.h
  ${MTB_PDL_CAT1_DIR}/drivers/include/cy_sysclk.h
  ${MTB_PDL_CAT1_DIR}/drivers/include/cy_sysint.h
  ${MTB_PDL_CAT1_DIR}/drivers/include/cy_syslib.h
  ${MTB_PDL_CAT1_DIR}/drivers/include/cy_syspm.h
  ${MTB_PDL_CAT1_DIR}/drivers/include/cy_systick.h
  ${MTB_PDL_CAT1_DIR}/drivers/include/cy_tcpwm.h
  ${MTB_PDL_CAT1_DIR}/drivers/include/cy_tcpwm_counter.h
  ${MTB_PDL_CAT1_DIR}/drivers/include/cy_tcpwm_pwm.h
  ${MTB_PDL_CAT1_DIR}/drivers/include/cy_tcpwm_quaddec.h
  ${MTB_PDL_CAT1_DIR}/drivers/include/cy_trigmux.h
  ${MTB_PDL_CAT1_DIR}/drivers/include/cy_usbfs_dev_drv.h
  ${MTB_PDL_CAT1_DIR}/drivers/include/cy_usbfs_dev_drv_pvt.h
  ${MTB_PDL_CAT1_DIR}/drivers/include/cy_usbfs_dev_drv_reg.h
  ${MTB_PDL_CAT1_DIR}/drivers/include/cy_wdt.h
  ${MTB_PDL_CAT1_DIR}/drivers/source/cy_ble_clk.c
  ${MTB_PDL_CAT1_DIR}/drivers/source/cy_canfd.c
  ${MTB_PDL_CAT1_DIR}/drivers/source/cy_crypto.c
  ${MTB_PDL_CAT1_DIR}/drivers/source/cy_crypto_core_aes_v1.c
  ${MTB_PDL_CAT1_DIR}/drivers/source/cy_crypto_core_aes_v2.c
  ${MTB_PDL_CAT1_DIR}/drivers/source/cy_crypto_core_cmac_v1.c
  ${MTB_PDL_CAT1_DIR}/drivers/source/cy_crypto_core_cmac_v2.c
  ${MTB_PDL_CAT1_DIR}/drivers/source/cy_crypto_core_crc_v1.c
  ${MTB_PDL_CAT1_DIR}/drivers/source/cy_crypto_core_crc_v2.c
  ${MTB_PDL_CAT1_DIR}/drivers/source/cy_crypto_core_des_v1.c
  ${MTB_PDL_CAT1_DIR}/drivers/source/cy_crypto_core_des_v2.c
  ${MTB_PDL_CAT1_DIR}/drivers/source/cy_crypto_core_ecc_domain_params.c
  ${MTB_PDL_CAT1_DIR}/drivers/source/cy_crypto_core_ecc_ecdsa.c
  ${MTB_PDL_CAT1_DIR}/drivers/source/cy_crypto_core_ecc_key_gen.c
  ${MTB_PDL_CAT1_DIR}/drivers/source/cy_crypto_core_ecc_nist_p.c
  ${MTB_PDL_CAT1_DIR}/drivers/source/cy_crypto_core_hmac_v1.c
  ${MTB_PDL_CAT1_DIR}/drivers/source/cy_crypto_core_hmac_v2.c
  ${MTB_PDL_CAT1_DIR}/drivers/source/cy_crypto_core_hw.c
  ${MTB_PDL_CAT1_DIR}/drivers/source/cy_crypto_core_hw_v1.c
  ${MTB_PDL_CAT1_DIR}/drivers/source/cy_crypto_core_mem_v1.c
  ${MTB_PDL_CAT1_DIR}/drivers/source/cy_crypto_core_mem_v2.c
  ${MTB_PDL_CAT1_DIR}/drivers/source/cy_crypto_core_prng_v1.c
  ${MTB_PDL_CAT1_DIR}/drivers/source/cy_crypto_core_prng_v2.c
  ${MTB_PDL_CAT1_DIR}/drivers/source/cy_crypto_core_rsa.c
  ${MTB_PDL_CAT1_DIR}/drivers/source/cy_crypto_core_sha_v1.c
  ${MTB_PDL_CAT1_DIR}/drivers/source/cy_crypto_core_sha_v2.c
  ${MTB_PDL_CAT1_DIR}/drivers/source/cy_crypto_core_trng_v1.c
  ${MTB_PDL_CAT1_DIR}/drivers/source/cy_crypto_core_trng_v2.c
  ${MTB_PDL_CAT1_DIR}/drivers/source/cy_crypto_core_vu.c
  ${MTB_PDL_CAT1_DIR}/drivers/source/cy_crypto_server.c
  ${MTB_PDL_CAT1_DIR}/drivers/source/cy_csd.c
  ${MTB_PDL_CAT1_DIR}/drivers/source/cy_ctb.c
  ${MTB_PDL_CAT1_DIR}/drivers/source/cy_ctdac.c
  ${MTB_PDL_CAT1_DIR}/drivers/source/cy_device.c
  ${MTB_PDL_CAT1_DIR}/drivers/source/cy_dma.c
  ${MTB_PDL_CAT1_DIR}/drivers/source/cy_dmac.c
  ${MTB_PDL_CAT1_DIR}/drivers/source/cy_efuse.c
  ${MTB_PDL_CAT1_DIR}/drivers/source/cy_flash.c
  ${MTB_PDL_CAT1_DIR}/drivers/source/cy_gpio.c
  ${MTB_PDL_CAT1_DIR}/drivers/source/cy_i2s.c
  ${MTB_PDL_CAT1_DIR}/drivers/source/cy_ipc_drv.c
  ${MTB_PDL_CAT1_DIR}/drivers/source/cy_ipc_pipe.c
  ${MTB_PDL_CAT1_DIR}/drivers/source/cy_ipc_sema.c
  ${MTB_PDL_CAT1_DIR}/drivers/source/cy_lpcomp.c
  ${MTB_PDL_CAT1_DIR}/drivers/source/cy_lvd.c
  ${MTB_PDL_CAT1_DIR}/drivers/source/cy_mcwdt.c
  ${MTB_PDL_CAT1_DIR}/drivers/source/cy_pdm_pcm.c
  ${MTB_PDL_CAT1_DIR}/drivers/source/cy_pra.c
  ${MTB_PDL_CAT1_DIR}/drivers/source/cy_pra_cfg.c
  ${MTB_PDL_CAT1_DIR}/drivers/source/cy_profile.c
  ${MTB_PDL_CAT1_DIR}/drivers/source/cy_prot.c
  ${MTB_PDL_CAT1_DIR}/drivers/source/cy_rtc.c
  ${MTB_PDL_CAT1_DIR}/drivers/source/cy_sar.c
  ${MTB_PDL_CAT1_DIR}/drivers/source/cy_scb_common.c
  ${MTB_PDL_CAT1_DIR}/drivers/source/cy_scb_ezi2c.c
  ${MTB_PDL_CAT1_DIR}/drivers/source/cy_scb_i2c.c
  ${MTB_PDL_CAT1_DIR}/drivers/source/cy_scb_spi.c
  ${MTB_PDL_CAT1_DIR}/drivers/source/cy_scb_uart.c
  ${MTB_PDL_CAT1_DIR}/drivers/source/cy_sd_host.c
  ${MTB_PDL_CAT1_DIR}/drivers/source/cy_seglcd.c
  ${MTB_PDL_CAT1_DIR}/drivers/source/cy_smartio.c
  ${MTB_PDL_CAT1_DIR}/drivers/source/cy_smif.c
  ${MTB_PDL_CAT1_DIR}/drivers/source/cy_smif_memslot.c
  ${MTB_PDL_CAT1_DIR}/drivers/source/cy_sysanalog.c
  ${MTB_PDL_CAT1_DIR}/drivers/source/cy_sysclk.c
  ${MTB_PDL_CAT1_DIR}/drivers/source/cy_sysint.c
  ${MTB_PDL_CAT1_DIR}/drivers/source/cy_syslib.c
  ${MTB_PDL_CAT1_DIR}/drivers/source/cy_syspm.c
  ${MTB_PDL_CAT1_DIR}/drivers/source/cy_systick.c
  ${MTB_PDL_CAT1_DIR}/drivers/source/cy_tcpwm_counter.c
  ${MTB_PDL_CAT1_DIR}/drivers/source/cy_tcpwm_pwm.c
  ${MTB_PDL_CAT1_DIR}/drivers/source/cy_tcpwm_quaddec.c
  ${MTB_PDL_CAT1_DIR}/drivers/source/cy_trigmux.c
  ${MTB_PDL_CAT1_DIR}/drivers/source/cy_usbfs_dev_drv.c
  ${MTB_PDL_CAT1_DIR}/drivers/source/cy_usbfs_dev_drv_io.c
  ${MTB_PDL_CAT1_DIR}/drivers/source/cy_usbfs_dev_drv_io_dma.c
  ${MTB_PDL_CAT1_DIR}/drivers/source/cy_wdt.c
)
set(MTB_PDL_CAT1_INCLUDE_DIRS
  ${MTB_PDL_CAT1_DIR}/devices/COMPONENT_CAT1A/include
  ${MTB_PDL_CAT1_DIR}/drivers/include
)
set(MTB_PDL_CAT1_LINK_LIBRARIES
  core-lib cmsis-core
)

if(${TOOLCHAIN} STREQUAL GCC)
  list(APPEND MTB_PDL_CAT1_SOURCES ${MTB_PDL_CAT1_DIR}/drivers/source/TOOLCHAIN_GCC_ARM/cy_syslib_gcc.S)
elseif(${TOOLCHAIN} STREQUAL ARM)
  list(APPEND MTB_PDL_CAT1_SOURCES ${MTB_PDL_CAT1_DIR}/drivers/source/TOOLCHAIN_ARM/cy_syslib_mdk.s)
elseif(${TOOLCHAIN} STREQUAL IAR)
  list(APPEND MTB_PDL_CAT1_SOURCES ${MTB_PDL_CAT1_DIR}/drivers/source/TOOLCHAIN_IAR/cy_syslib_iar.s)
elseif(${TOOLCHAIN} STREQUAL LLVM)
  list(APPEND MTB_PDL_CAT1_SOURCES ${LLVM_PORT_DIR}/syslib/cy_syslib_clang.S)
else()
  message(FATAL_ERROR "mtb-pdl-cat1: TOOLCHAIN ${TOOLCHAIN} is not supported.")
endif()

add_library(mtb-pdl-cat1 STATIC EXCLUDE_FROM_ALL ${MTB_PDL_CAT1_SOURCES})
target_include_directories(mtb-pdl-cat1 PUBLIC ${MTB_PDL_CAT1_INCLUDE_DIRS})
target_link_libraries(mtb-pdl-cat1 PUBLIC ${MTB_PDL_CAT1_LINK_LIBRARIES})
