set(PORT_DIR ${CMAKE_SOURCE_DIR}/os/noos)

# Load CM0+ application definitions
if(${CORE} STREQUAL CM0P)
  include(${PORT_DIR}/cm0p-sleep.cmake)
  return()
endif()

# Load CM4 application definitions
include(app/ble-findme.cmake)
include(app/capsense-buttons-slider.cmake)
include(app/crypto-aes.cmake)
include(app/crypto-sha.cmake)
include(app/crypto-trng.cmake)
include(app/empty-app.cmake)
include(app/emulated-eeprom.cmake)
include(app/fault-handling.cmake)
include(app/gpio-interrupt.cmake)
include(app/hello-world.cmake)
include(app/i2c-master-ezi2c-slave.cmake)
include(app/i2c-master.cmake)
include(app/i2c-slave-callback.cmake)
include(app/i2s.cmake)
include(app/mcwdt.cmake)
include(app/pdm-pcm.cmake)
include(app/pdm-to-i2s.cmake)
include(app/pwm-square-wave.cmake)
include(app/qspi-fram-access.cmake)
include(app/qspi-readwrite-sfdp.cmake)
include(app/qspi-readwrite.cmake)
include(app/rtc-basics.cmake)
include(app/smartio-ramping-led.cmake)
include(app/spi-master-dma.cmake)
include(app/spi-master.cmake)
include(app/switching-power-modes.cmake)
include(app/uart-transmit-receive-dma.cmake)
include(app/uart-transmit-receive.cmake)
include(app/usb-audio-recorder.cmake)
include(app/usb-cdc-echo.cmake)
include(app/usb-hid-generic.cmake)
include(app/usb-hid-mouse.cmake)
include(app/usb-msc-logger.cmake)
include(app/wdt.cmake)

# Load CMSIS tests
include(test/cmsis/CoreValidation.cmake)
